# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    # Use ["main", "master"] for CI only on the default branch.
    # Use ["**"] for CI on all branches.
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        # Update this as needed:
        # Common platforms: ["ubuntu-latest", "macos-latest", "windows-latest"]
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.12", "3.13"]

    # Linux only by default. Use ${{ matrix.os }} for other OSes.
    runs-on: ${{ matrix.os }}

    steps:
      # Generally following uv docs:
      # https://docs.astral.sh/uv/guides/integration/github/

      - name: Checkout (official GitHub action)
        uses: actions/checkout@v4
        with:
          # Important for versioning plugins:
          fetch-depth: 0

      # From debugging the cydifflib build failure.
      # Confirmed we have version 3.31.6 installed.
      - name: Display CMake Version
        run: cmake --version

      - name: Install uv (official Astral action)
        uses: astral-sh/setup-uv@v5
        with:
          # Update this as needed:
          version: "0.6.12"
          enable-cache: false
          python-version: ${{ matrix.python-version }}

      - name: Set up Python (using uv)
        run: uv python install

      - name: Install all dependencies
        run: uv sync --all-extras --dev
        # env:
          # Unclear why this should be needed since we already have a newer CMake,
          # but it seems to be needed when building cydifflib.
          # CMAKE_ARGS: "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"


      - name: Run linting
        run: uv run python devtools/lint.py

      - name: Run tests
        run: uv run pytest